#!/usr/bin/env python
#coding=utf-8

import os

MY_PROGRAM = "my_script/generate_readme.sh"
OK = 0
ERROR = -1

def main():
    if not os.system("bash " + MY_PROGRAM):
        os.system("git add README.md")
        return OK
    else:
        return ERROR

if __name__ == "__main__":
    main()
